### ISSUE TITLE
Windows blocks me from downloading the invisible dual fix dll file

### ISSUE THREAD

**Issue by PizzaTacos** [matcool/small-gd-mods#3]
So I know the solution to solving this, just manually allow it, but I thought I would bring this to light

**Comment by matcool** [comment]
thats not even my mod??

**Comment by poweredbypie** [comment]
bro thats my mod why are you telling this to mat

**Comment by PizzaTacos** [comment]
Sorry, I was thinking of the wrong thing, I meant to say the run info. I'm sorry I got that wrong lol
