### ISSUE TITLE
Add README for clear and accessible installation instructions

### ISSUE THREAD

**Issue by benjamin-andersen** [matcool/small-gd-mods#4]
### Steps to reproduce:
- put `run-info.dll` file inside `steamapps/common/Geometry Dash/extensions` folder
- launch game, hit tab

### Expected result:
MegaHack loads the extension

### Actual result:
MegaHack does not load the extension

![image](https://user-images.githubusercontent.com/70706530/124540081-8e4a3d00-ddd3-11eb-89fd-7041704cfede.png)
![image](https://user-images.githubusercontent.com/70706530/124540117-9b672c00-ddd3-11eb-9f73-228e308d9322.png)

(Note: I am aware this is a beta build, but I opened this issue in case this persists in later, stable builds)

**Comment by matcool** [comment]
download minhook, as stated in the install instructions

**Comment by benjamin-andersen** [comment]
Can we add a README so that this is less confusing? You have one set of installation instructions on the release _(which is very uncommon anyways, installation instructions typically reside in a README)_ and another completely different set on a different website.

I can't imagine other people haven't gotten confused by this, so this would be nice for people who are unfamiliar with your repository. Not trying to be harsh, just letting you know how you can improve :)

**Comment by matcool** [comment]
The ones on github releases are outdated, they will be removed soon

**Comment by benjamin-andersen** [comment]
I made a PR to add a README :)
